[package]
name = "sidewars"
version = "0.1.0"
authors = ["LFalch <lucas@wasd.dk>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10.1"
self-compare = "0.2.0"
rand = "0.8.5"
